name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version of the release (e.g. v0.1.0)"
        required: true
        type: string

jobs:
  build:
    name: Build app bundle
    strategy:
      matrix:
        include:
          - runs-on: macos-latest
            args: "aarch64-apple-darwin"
          - runs-on: macos-latest
            args: "x86_64-apple-darwin"
          - runs-on: windows-latest
            args: "x86_64-pc-windows-msvc"
          - runs-on: ubuntu-latest
            args: "x86_64-unknown-linux-gnu"
    runs-on: ${{ matrix.runs-on }}
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.TEMP_SSH_KEY }}
          submodules: recursive

      - name: Import signing certificate into keychain
        if: runner.os == 'macOS'
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev

      - name: Setup just cli
        uses: extractions/setup-just@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.args }}
          components: rust-src, rustfmt, clippy

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "^3.13"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: src-daemon/go.mod
          cache-dependency-path: src-daemon/go.sum

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Project dependencies
        run: bun install --cwd src-frontend

      - name: Build app (macOS)
        if: runner.os == 'macOS'
        run: |
          GITHUB_CI=1 just package ${{ matrix.args }}

          # Create artifacts directory
          mkdir -p artifacts

          mv src-tauri/target/${{ matrix.args }}/release/bundle/dmg/*.dmg artifacts/SyftBox-${{ matrix.args }}.dmg
          mv src-tauri/target/${{ matrix.args }}/release/bundle/macos/*.app.tar.gz artifacts/SyftBox-${{ matrix.args }}.app.tar.gz
          mv src-tauri/target/${{ matrix.args }}/release/bundle/macos/*.app.tar.gz.sig artifacts/SyftBox-${{ matrix.args }}.app.tar.gz.sig

      - name: Build app (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $env:GITHUB_CI = "1"; just package ${{ matrix.args }}

          # Create artifacts directory
          New-Item -Path artifacts -ItemType Directory -Force

          Move-Item -Path src-tauri\target\${{ matrix.args }}\release\bundle\msi\*.msi -Destination artifacts\SyftBox-${{ matrix.args }}.msi
          Move-Item -Path src-tauri\target\${{ matrix.args }}\release\bundle\msi\*.msi.sig -Destination artifacts\SyftBox-${{ matrix.args }}.msi.sig

      - name: Build app (Linux)
        if: runner.os == 'Linux'
        run: |
          GITHUB_CI=1 just package ${{ matrix.args }}

          # Create artifacts directory
          mkdir -p artifacts

          mv src-tauri/target/${{ matrix.args }}/release/bundle/deb/*.deb artifacts/SyftBox-${{ matrix.args }}.deb
          mv src-tauri/target/${{ matrix.args }}/release/bundle/rpm/*.rpm artifacts/SyftBox-${{ matrix.args }}.rpm
          mv src-tauri/target/${{ matrix.args }}/release/bundle/appimage/*.appimage artifacts/SyftBox-${{ matrix.args }}.appimage

      - name: Setup git config
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"

      - name: Push changes to the repo
        run: |
          # Create a new tag for the release
          git tag ${{ inputs.version }}

          # Set a new remote URL using HTTPS with the github token
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git

          # Push the tag to the remote repo
          git push origin ${{ inputs.version }}

      # - name: Deploy frontend to syftbox-stage
      #   run: just deploy-frontend-to-stage

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.version }}
          name: ${{ inputs.version }}
          draft: true
          allowUpdates: true
          omitBodyDuringUpdate: true
          generateReleaseNotes: true
          makeLatest: true
          artifacts: |
            ./artifacts/*.app.tar.gz
            ./artifacts/*.app.tar.gz.sig

            ./artifacts/*.appimage
            ./artifacts/*.appimage.sig

            ./artifacts/*.deb
            ./artifacts/*.deb.sig

            ./artifacts/*.dmg
            ./artifacts/*.dmg.sig

            ./artifacts/*.msi
            ./artifacts/*.msi.sig

            ./artifacts/*.rpm
            ./artifacts/*.rpm.sig

      - name: Clean up all user keychains
        if: always() && runner.os == 'macOS'
        run: |
          # List all keychains
          keychains=$(security list-keychains | tr -d '" "')

          # Iterate over the keychains and delete each one that is not a system keychain
          echo "$keychains" | while IFS= read -r keychain; do
            if [[ "$keychain" != "/Library/Keychains/System.keychain" && "$keychain" != "/Library/Keychains/SystemRootCertificates.keychain" ]]; then
              echo "Deleting keychain: $keychain"
              security delete-keychain "$keychain"
            else
              echo "Skipping system keychain: $keychain"
            fi
          done
