name: Generate Release Notes

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the release (e.g. v0.1.22)"
        required: true
        default: v0.1.22
        type: string

jobs:
  generate-release-notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          submodules: recursive

      - name: Generate Release Notes
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          set -xv

          # Make the script executable
          chmod +x ./scripts/generate-release-notes.sh

          # Generate release notes and save to a file
          ./scripts/generate-release-notes.sh > release_notes.md

          # Update the release with the generated notes
          gh release edit ${{ inputs.version }} --notes-file release_notes.md
