name: Generate Release JSON

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate and upload release.json
        id: generate
        shell: bash
        run: just generate-release-json ${{ github.event.release.tag_name }} yes
