name: Lint

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Get cache key
        id: cache-key
        run: echo "key=$(sha256sum bun.lockb | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Run linters
        run: |
          bun prettier --check .
          bun run lint
          # bun tsc --noEmit
          bun commitlint --from=HEAD~1
